spring:
  application:
    name: api-gateway
server:
  port: 8080
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}

zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    ms-pessoa:
      path: /pessoa/**
      serviceUd: ms-pessoa
  host:
    socket-timeout-millis: 30000